Update patch set 1
Patch Set 1: I would prefer that you didn't submit this

Breaks compiling with the 4.4.3 compiler: 

cc1: error: -Werror=maybe-uninitialized: No option -Wmaybe-uninitialized
cc1: warnings being treated as errors
/home/aorth/android/CM9/kernel/samsung/smdk4210/scripts/mod/empty.c:1: error: switch -mcpu=cortex-a9 conflicts with -march= switch

Patch-set: 1