Update patch set 1
Patch Set 1: Do not submit

kernel/built-in.o: In function `exynos_gpufreq_lock':
/android/cm-10.1/kernel/samsung/smdk4210/arch/arm/mach-exynos/include/mach/gpufreq.h:20: undefined reference to `mali_dvfs_bottom_lock_push'
kernel/built-in.o: In function `exynos_gpufreq_unlock':
/android/cm-10.1/kernel/samsung/smdk4210/arch/arm/mach-exynos/include/mach/gpufreq.h:25: undefined reference to `mali_dvfs_bottom_lock_pop'
kernel/built-in.o: In function `exynos_gpufreq_lock':
/android/cm-10.1/kernel/samsung/smdk4210/arch/arm/mach-exynos/include/mach/gpufreq.h:20: undefined reference to `mali_dvfs_bottom_lock_push'
kernel/built-in.o: In function `exynos_gpufreq_unlock':
/android/cm-10.1/kernel/samsung/smdk4210/arch/arm/mach-exynos/include/mach/gpufreq.h:25: undefined reference to `mali_dvfs_bottom_lock_pop'

todo:
- cypress touchkey missing? led timeout?
- add deleted gitignores back
- update defconfigs

Patch-set: 1